# Generated by Django 4.2.6 on 2023-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_tg_subscribed",
            field=models.BooleanField(default=False),
        ),
    ]
