# Generated by Django 4.2.6 on 2023-10-24 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_balancehistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="is_tg_subscribed",
        ),
        migrations.CreateModel(
            name="CustomerNotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enable_telegram", models.BooleanField(default=False)),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("enable_email", models.BooleanField(default=False)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
